import bahrudin.quiz.Item;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import bahrudin.quiz.ComboBoxModel;
import bahrudin.quiz.TableModel;
import bahrudin.quiz.Transaksi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bahrudin<bahrudinrizky313@gmai.com>
 */
public class FormTransaksi extends javax.swing.JFrame {
    
    private int id = 0; //digunakan untuk memberikan nomor pada transaksi
    private String code; //untuk menyimpan code transaksi
    private DefaultComboBoxModel cbModel; //jComboBox model
    private DefaultTableModel tbModel;  //jTable Model
    private final ArrayList<Item> cart = new ArrayList<>();//menyimpan item yang dibeli 

    public FormTransaksi() {
        ComboBoxModel cbModel = new ComboBoxModel(); //mengeset combobox item
        this.cbModel = new DefaultComboBoxModel<>(cbModel.getNames().toArray()); 
        
        TableModel tbModel = new TableModel(); //mengset nama kolom pada table transaksi
        this.tbModel = new DefaultTableModel(tbModel.getcolumnName(), 0); 
        
        initComponents();
    }
   //menambahkan nomor baru 
    private void incId(){
        this.id += 1;
    }
    //manghapus / mengurangi nomor
    private void decId(){
        this.id -= 1;
    }
    
    //mengset code transaksi yang sesuai dengan tanggal sekarang
    private String setCode(){
        this.incId();
        String set = new SimpleDateFormat("yyMMdd").format(new Date());
        this.code = String.format(set+"%02d",this.id);
        return code;
    }
    
    //menambah item pada tabel
    private Object[] addItem(String nama, int jumlah){
        float harga = 0;
        ComboBoxModel item = new ComboBoxModel();
        for(int i=0; i<item.getNames().size(); i++){
            if(nama.equalsIgnoreCase(item.getNames().get(i))){
                harga = item.getPrices().get(i);
            }
        }
        Object[] obj={
            nama,harga,jumlah
        };
        return obj;
    }
    
    //mengupdate jumlah
    private  void updateJumlah (String nama , int add) {
        ArrayList<String> item = new ArrayList<> () ;
        for (int i = 0; i < tbModel.getRowCount(); i++) {
            item.add (tbModel.getValueAt (i , 0).toString()) ;
        }
        for (int i = 0; i < item.size(); i++) {
            if (item.get(i).equals(nama)) {
                int jumlah = new Integer (tbModel.getValueAt(i , 2).toString()) ;
                tbModel.setValueAt (jumlah + add , i , 2) ;
            }
        }
    }
    //melakukan pengecekan apakah barang yang dipilih sudah ada pada tabel atau belum
    private boolean isDuplicate (String nama){
        boolean result = false ;
        ArrayList <String> item = new ArrayList<>() ;
        for (int i = 0; i < tbModel.getRowCount(); i++) {
            item.add (tbModel.getValueAt(i, 0).toString()) ;
        }
        for (String i : item) {
            if (i.equals(nama)) {
                result = true ;
            }
        }
        
        return result ;
    }
    
    //pengecekan apakah barrang kosong
    private boolean isEmpty() {
        return this.tblListItems.getRowCount() <= 0 ;
    }
    
    //mendisable tombol save dan remove ketika tabel masih kosong
    private void belanja() {
        if (isEmpty()) {
            this.btnSave.setEnabled(false) ;
            this.btnRmv.setEnabled(false) ;
        } else {
            this.btnSave.setEnabled(true) ;
            this.btnRmv.setEnabled(true) ;
        }
    }
        
    //melakukan transaksi baru ketika transaksi sebelumnya telah sukses
     private void transaksiBaru () {
        this.txtJml.setText(" ") ;
        this.txtCode.setText(" ") ;
        this.btnNew.setEnabled(true) ;
        this.btnSave.setEnabled(false) ;
        this.btnCncl.setEnabled(false) ;
        this.btnAdd.setEnabled(false) ;
        this.btnRmv.setEnabled(false) ;
        this.btnRmv.setEnabled(false) ;
        this.txtJml.setEnabled(false) ;
        this.comboItems.setEnabled(false) ;
        this.tbModel.setRowCount(0) ;
        this.cart.clear() ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        comboItems = new javax.swing.JComboBox<>();
        btnNew = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRmv = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCncl = new javax.swing.JButton();
        txtJml = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Code");

        jLabel2.setText("Items");

        comboItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Susu", "Gula" }));
        comboItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemsActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRmv.setText("Remove");
        btnRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCncl.setText("Cancel");
        btnCncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCnclActionPerformed(evt);
            }
        });

        tblListItems.setModel(this.tbModel);
        jScrollPane1.setViewportView(tblListItems);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCode, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(comboItems, 0, 203, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCncl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRmv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRmv)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCncl))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//penambahan action pada button new
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.txtJml.setText("1");
        this.btnNew.setEnabled(false);
        this.btnCncl.setEnabled(true);
        this.btnAdd.setEnabled(true);
        this.txtJml.setEnabled(true);
        this.comboItems.setEnabled(true);
        this.txtCode.setText(this.setCode());
    }//GEN-LAST:event_btnNewActionPerformed

    private void comboItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemsActionPerformed
//menambahkan action pada button cancel
    private void btnCnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCnclActionPerformed
        transaksiBaru();
        this.decId();
    }//GEN-LAST:event_btnCnclActionPerformed
//menambahkan action pada button add
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String nama = this.comboItems.getSelectedItem().toString(); 
        int jumlah = new Integer(this.txtJml.getText()); 
        if(isDuplicate(nama)) { 
   
            updateJumlah(nama, jumlah);
        } else {
            tbModel.addRow(addItem(nama, jumlah));
        }
        this.belanja();
    }//GEN-LAST:event_btnAddActionPerformed
//menambahkan action pada button remove
    private void btnRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvActionPerformed
       if(tblListItems.getSelectedRow()<0) { 
            String str = "Pilih item yang ingin dihapus !"; 
            JOptionPane.showMessageDialog(this, str, "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int count = tblListItems.getSelectedRows().length;
            for(int i = 0; i < count; i++) {
                tbModel.removeRow(tblListItems.getSelectedRow());
            }
        
        this.belanja();
    }                                      
    }//GEN-LAST:event_btnRmvActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try { //loop setiap tabel
            for (int i = 0; i < tbModel.getRowCount(); i++) {                   
                String nama = tbModel.getValueAt(i, 0).toString();  //menyiapkan nama dan jumlah menjadi variable            
                float harga = new Float(tbModel.getValueAt(i, 1).toString());   
                int jumlah = new Integer(tbModel.getValueAt(i, 2).toString());     
                this.cart.add(new Item(nama, harga, jumlah));
            }
            //instansiasi kelas transaksi dengan kode dengan commited belanja
            Transaksi transaksi = new Transaksi(this.code, this.cart);
            StringBuilder toSrting = new StringBuilder();
            toSrting.append(transaksi.transDetail()); //memanggil dialog dengan StringBuilder
            JOptionPane.showMessageDialog(this, toSrting, "Information", JOptionPane.INFORMATION_MESSAGE);
            transaksiBaru(); 
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCncl;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRmv;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboItems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListItems;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtJml;
    // End of variables declaration//GEN-END:variables
}
    
